import type { AppProps } from "next/app";
import Head from "next/head";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "../../styles/globals.scss";

import "../../styles/main.scss";

import { useEffect, useState } from "react";
import { Provider } from "react-redux";
import { store } from "../../store";

function MyApp({ Component, pageProps }: AppProps) {
  if (typeof window === "undefined") {
    return <></>;
  } else {
    return (
      <Provider store={store}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hydrated>
          <Component {...pageProps} />
        </Hydrated>
      </Provider>
    );
  }
}

export default MyApp;

const Hydrated = ({ children }: { children?: any }) => {
  const [hydration, setHydration] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setHydration(true);
    }
  }, []);
  return hydration ? children : "";
};
